---
# tasks file for nextcloud

- name: include os specific tasks
  include_tasks: 'os/main.yml'

- name: download nextcloud archive
  get_url:
    url:  "{{ nextcloud_archive }}"
    dest: /tmp/nextcloud.tar.bz2
    checksum: "sha256:{{ nextcloud_archive }}.sha256"

- name: install nextcloud
  unarchive: 
    src: /tmp/nextcloud.tar.bz2
    dest: /var/www
    remote_src: true
    owner: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
    group: "{{ web_group[nextcloud_webserver_type][ansible_os_family] }}"
    mode:  "o-rwx"
    creates: "{{ nextcloud_www_dir }}/occ"

- name: include selinux tasks
  include_tasks: selinux.yml
  when: 
    - (ansible_os_family == "RedHat")
    - ('status' in ansible_selinux)
    - (ansible_selinux.status == "enabled")

- name: flush all handlers to restart server
  meta: flush_handlers

- name: configure nextcloud
  include_tasks: configure/nextcloud.yml

- name: add nextcloud cronjob
  cron:
    name: nextcloud cronjob
    minute: '*/5'
    user: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
    job: "php -f {{ nextcloud_www_dir }}/cron.php > /dev/null 2>&1"

- name: run nextcloud cronjob
  become_user: "{{ web_user[nextcloud_webserver_type][ansible_os_family] }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  shell: php -f {{ nextcloud_www_dir }}/cron.php
  args:
    chdir: "{{ nextcloud_www_dir }}"
  when: first_setup_nextcloud is changed

- name: configure onlyoffice
  include_tasks: configure/onlyoffice.yml
  when: install_onlyoffice|bool


post_tasks:
  - name: check install status
    uri:
      url: https://{{ nextcloud_fqdn }}/status.php
      return_content: yes
      validate_certs: "{% if (nextcloud_certificate_type == 'selfsigned') or nextcloud_certificate_test %}no{% else %}yes{% endif %}"
    register: nextcloud_status